// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaqlEgrs3bUv2LHIYQNf-uLkul6pB-72Y',
    appId: '1:966163984411:web:ed0cf3960e8c84f838c8be',
    messagingSenderId: '966163984411',
    projectId: 'task-2ec58',
    authDomain: 'task-2ec58.firebaseapp.com',
    storageBucket: 'task-2ec58.firebasestorage.app',
    measurementId: 'G-7Q4B43W9W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtTaQLHMMj_S2W2FJLJcDV3RANZFQOsVI',
    appId: '1:966163984411:android:88058a71ebf35a8338c8be',
    messagingSenderId: '966163984411',
    projectId: 'task-2ec58',
    storageBucket: 'task-2ec58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBafD4pOErhUd4vtoIg0AixTUNqpdwxtCU',
    appId: '1:966163984411:ios:511470c8e76e168338c8be',
    messagingSenderId: '966163984411',
    projectId: 'task-2ec58',
    storageBucket: 'task-2ec58.firebasestorage.app',
    iosBundleId: 'com.example.enenni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBafD4pOErhUd4vtoIg0AixTUNqpdwxtCU',
    appId: '1:966163984411:ios:511470c8e76e168338c8be',
    messagingSenderId: '966163984411',
    projectId: 'task-2ec58',
    storageBucket: 'task-2ec58.firebasestorage.app',
    iosBundleId: 'com.example.enenni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaqlEgrs3bUv2LHIYQNf-uLkul6pB-72Y',
    appId: '1:966163984411:web:2847cceb3015857d38c8be',
    messagingSenderId: '966163984411',
    projectId: 'task-2ec58',
    authDomain: 'task-2ec58.firebaseapp.com',
    storageBucket: 'task-2ec58.firebasestorage.app',
    measurementId: 'G-PY8F9HR4PT',
  );
}
